server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.gwinseapptest.online
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: http-01-production
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

configs:
  params:
    server.insecure: true
